export const search = {"Search":[{"Title":"Gran Torino","Year":"2008","imdbID":"tt1205489","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BMTc5NTk2OTU1Nl5BMl5BanBnXkFtZTcwMDc3NjAwMg@@._V1_SX300.jpg"},{"Title":"Gran Casino","Year":"1947","imdbID":"tt0039434","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTc0NDExMDUzN15BMl5BanBnXkFtZTcwNDE0OTM1MQ@@._V1_SX300.jpg"},{"Title":"Gran Turismo 4","Year":"2004","imdbID":"tt0317600","Type":"game","Poster":"http://ia.media-imdb.com/images/M/MV5BMTg5MDE4MDM0Nl5BMl5BanBnXkFtZTcwMzQ1MzE2MQ@@._V1_SX300.jpg"},{"Title":"Gran Turismo 3: A-Spec","Year":"2001","imdbID":"tt0274533","Type":"game","Poster":"http://ia.media-imdb.com/images/M/MV5BMTI3NDIyNDIxNl5BMl5BanBnXkFtZTcwODc3MDE2MQ@@._V1_SX300.jpg"},{"Title":"Gran Turismo","Year":"1998","imdbID":"tt0190428","Type":"game","Poster":"http://ia.media-imdb.com/images/M/MV5BNzI5YWQ3OWMtNDY2Mi00Njc2LWEyYTktMWQ3ZjMwYzQ3NGEyXkEyXkFqcGdeQXVyNjExODE1MDc@._V1_SX300.jpg"},{"Title":"La gran final","Year":"2006","imdbID":"tt0476240","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTg3OTgyNzAyMF5BMl5BanBnXkFtZTcwMDYyOTI0MQ@@._V1_SX300.jpg"},{"Title":"Quel gran pezzo della Ubalda tutta nuda e tutta calda","Year":"1972","imdbID":"tt0070583","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BYmJiODhiZGItM2FlZS00YjcxLTljOTktNmRiMDFmM2ExMWI0XkEyXkFqcGdeQXVyMjU5OTg5NDc@._V1_SX300.jpg"},{"Title":"Gran Turismo 2","Year":"1999","imdbID":"tt0245138","Type":"game","Poster":"http://ia.media-imdb.com/images/M/MV5BMTM2ODEyNzg1M15BMl5BanBnXkFtZTcwNTU1MzkyMQ@@._V1_SX300.jpg"},{"Title":"Super Gran","Year":"1985–1987","imdbID":"tt0134264","Type":"series","Poster":"https://m.media-amazon.com/images/M/MV5BNjYzNTY4NmItMGM5ZC00NWM0LWJjZDktMWI1Y2M1MjJmNjhhXkEyXkFqcGdeQXVyMjM2ODYwMQ@@._V1_SX300.jpg"},{"Title":"La gran familia","Year":"1962","imdbID":"tt0056037","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BYzQzNjE1ZGYtMDA4ZC00MzJiLThmYjMtN2YzNzllN2Q3Nzg4XkEyXkFqcGdeQXVyMTY5MDE5NA@@._V1_SX300.jpg"},{
"Title":"Star Wars: Episode IV - A New Hope",
"Year":"1977",
"imdbID":"tt0076759",
"Type":"movie",
"Poster":
"https://images-na.ssl-images-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg"}

,{"Title":"Star Wars: Episode V - The Empire Strikes Back","Year":"1980","imdbID":"tt0080684","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BYmU1NDRjNDgtMzhiMi00NjZmLTg5NGItZDNiZjU5NTU4OTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg"},{"Title":"Star Wars: Episode VI - Return of the Jedi","Year":"1983","imdbID":"tt0086190","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BOWZlMjFiYzgtMTUzNC00Y2IzLTk1NTMtZmNhMTczNTk0ODk1XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg"},{"Title":"Star Wars: The Force Awakens","Year":"2015","imdbID":"tt2488496","Type":"movie","Poster":"https://ia.media-imdb.com/images/M/MV5BOTAzODEzNDAzMl5BMl5BanBnXkFtZTgwMDU1MTgzNzE@._V1_SX300.jpg"},{"Title":"Star Wars: Episode I - The Phantom Menace","Year":"1999","imdbID":"tt0120915","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BYTRhNjcwNWQtMGJmMi00NmQyLWE2YzItODVmMTdjNWI0ZDA2XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg"},{"Title":"Star Wars: Episode III - Revenge of the Sith","Year":"2005","imdbID":"tt0121766","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNTc4MTc3NTQ5OF5BMl5BanBnXkFtZTcwOTg0NjI4NA@@._V1_SX300.jpg"},{"Title":"Star Trek","Year":"2009","imdbID":"tt0796366","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjE5NDQ5OTE4Ml5BMl5BanBnXkFtZTcwOTE3NDIzMw@@._V1_SX300.jpg"},{"Title":"Star Wars: Episode II - Attack of the Clones","Year":"2002","imdbID":"tt0121765","Type":"movie","Poster":"https://ia.media-imdb.com/images/M/MV5BOWNkZmVjODAtNTFlYy00NTQwLWJhY2UtMmFmZTkyOWJmZjZiL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg"},{"Title":"Star Trek: Into Darkness","Year":"2013","imdbID":"tt1408101","Type":"movie","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTk2NzczOTgxNF5BMl5BanBnXkFtZTcwODQ5ODczOQ@@._V1_SX300.jpg"},{"Title":"Rogue One: A Star Wars Story","Year":"2016","imdbID":"tt3748528","Type":"movie","Poster":"https://ia.media-imdb.com/images/M/MV5BMjEwMzMxODIzOV5BMl5BanBnXkFtZTgwNzg3OTAzMDI@._V1_SX300.jpg"}],"totalResults":"3049","Response":"True"}

export const movie = {
  "Title":"Star Wars: Episode IV - A New Hope","Year":"1977","Rated":"PG","Released":"25 May 1977","Runtime":"121 min","Genre":"Action, Adventure, Fantasy","Director":"George Lucas","Writer":"George Lucas","Actors":"Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing","Plot":"Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle-station while also attempting to rescue Princess Leia from the evil Darth Vader.","Language":"English","Country":"USA","Awards":"Won 6 Oscars. Another 50 wins & 28 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.6/10"},{"Source":"Rotten Tomatoes","Value":"93%"},{"Source":"Metacritic","Value":"90/100"}],"Metascore":"90","imdbRating":"8.6","imdbVotes":"1,035,722","imdbID":"tt0076759","Type":"movie","DVD":"21 Sep 2004","BoxOffice":"N/A","Production":"20th Century Fox","Website":"http://www.starwars.com/episode-iv/","Response":"True"}
